import React, { useState, useRef, useEffect, useCallback } from "react"
import {
  View,
  StyleSheet,
  BackHandler,
  ToastAndroid,
  Platform,
  ActivityIndicator,
  Text,
  TouchableOpacity,
  SafeAreaView,
} from "react-native"
import { StatusBar } from "expo-status-bar"
import { WebView, WebViewMessageEvent } from "react-native-webview"

// Import inlined web bundle generated by scripts/generate-mobile-bundle.js
// @ts-ignore - Generated build artifact
import { webAppHtml } from "./src-mobile/generated/webAppHtml"

// Brand Colors
const BRAND_NAVY = "#05297A"
const BRAND_YELLOW = "#F0D225"
const BRAND_WHITE = "#FFFFFF"

interface WebNavigationState {
  tab: "login" | "bolsillo"
  hasOpenSheet: boolean
  hasOpenTutorial: boolean
  activeSheetName: string | null
}

/**
 * Error Boundary to catch render and mount errors in React Native
 */
interface AppErrorBoundaryProps {
  children: React.ReactNode;
  fallback?: React.ReactNode;
  onReset?: () => void;
}

interface AppErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
}

export class AppErrorBoundary extends React.Component<
  AppErrorBoundaryProps,
  AppErrorBoundaryState
> {
  constructor(props: AppErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error) {
    return { hasError: true, error }
  }

  componentDidCatch(error: Error, info: React.ErrorInfo) {
    console.error("AppErrorBoundary caught an error:", error, info)
  }

  render() {
    if (this.state.hasError) {
      return (
        <SafeAreaView style={styles.errorContainer}>
          <StatusBar hidden={true} />
          <View style={styles.errorCard}>
            <View style={styles.brandDotsContainer}>
              <View style={[styles.dot, styles.bigDot]} />
              <View style={[styles.dot, styles.smallDot]} />
              <View style={[styles.dot, styles.smallDot]} />
            </View>
            <Text style={styles.errorTitle}>Amigo BanCoppel</Text>
            <Text style={styles.errorMessage}>
              Ocurrió un problema al inicializar la aplicación.
            </Text>
            {__DEV__ && this.state.error && (
              <Text style={styles.errorDetails}>
                {this.state.error.message}
              </Text>
            )}
            <TouchableOpacity
              style={styles.retryButton}
              onPress={() => {
                this.setState({ hasError: false, error: null })
                this.props.onReset?.()
              }}
              activeOpacity={0.8}
            >
              <Text style={styles.retryButtonText}>Reintentar</Text>
            </TouchableOpacity>
          </View>
        </SafeAreaView>
      )
    }
    return this.props.children
  }
}

/**
 * Branded Loading Screen shown while the HTML bundle parses
 */
export function BrandLoadingView() {
  return (
    <View style={styles.loadingContainer}>
      <ActivityIndicator size="large" color={BRAND_YELLOW} />
    </View>
  )
}

/**
 * Main Mobile Wrapper Root Component
 */
export default function App() {
  const webViewRef = useRef<WebView>(null)
  const backPressCountRef = useRef(0)
  const [reloadKey, setReloadKey] = useState(0)

  // Synchronized state from the web application
  const [webState, setWebState] = useState<WebNavigationState>({
    tab: "login",
    hasOpenSheet: false,
    hasOpenTutorial: false,
    activeSheetName: null,
  })

  const handleReset = useCallback(() => {
    setReloadKey((prev) => prev + 1)
  }, [])

  /**
   * Handle messages sent from the React web app via window.ReactNativeWebView.postMessage
   */
  const handleMessage = useCallback((event: WebViewMessageEvent) => {
    try {
      const data = JSON.parse(event.nativeEvent.data)
      if (data.type === "NAV_STATE_UPDATE") {
        setWebState({
          tab: data.tab || "login",
          hasOpenSheet: !!data.hasOpenSheet,
          hasOpenTutorial: !!data.hasOpenTutorial,
          activeSheetName: data.activeSheetName || null,
        })
      }
    } catch {
      // Ignore unformatted string messages
    }
  }, [])

  /**
   * Android Hardware Back Button Gating
   */
  useEffect(() => {
    if (Platform.OS !== "android") return

    const onBackPress = (): boolean => {
      // 1. If a bottom sheet or tutorial is open, dismiss it
      if (webState.hasOpenSheet || webState.hasOpenTutorial) {
        webViewRef.current?.injectJavaScript(`
          (function() {
            window.dispatchEvent(new CustomEvent('android:hardwareBack'));
            window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', code: 'Escape', keyCode: 27, which: 27, bubbles: true }));
            var closeBtn = document.querySelector('[role="dialog"] button[aria-label="Cerrar"]');
            if (closeBtn) closeBtn.click();
            return true;
          })();
          true;
        `)
        return true // Consumes event, does NOT exit app
      }

      // 2. If on the 'bolsillo' (Amigo BanCoppel) dashboard, return to 'login' (Bienvenido)
      if (webState.tab === "bolsillo") {
        webViewRef.current?.injectJavaScript(`
          (function() {
            window.dispatchEvent(new CustomEvent('android:navigateToLogin'));
            var loginTab = document.querySelectorAll('[role="tab"]')[0];
            if (loginTab) loginTab.click();
            return true;
          })();
          true;
        `)
        return true // Consumes event, does NOT exit app
      }

      // 3. If on the 'login' screen with no modals, apply Double-Back-to-Exit safety pattern
      if (backPressCountRef.current === 0) {
        backPressCountRef.current = 1
        if (Platform.OS === "android") {
          ToastAndroid.show("Presiona de nuevo para salir", ToastAndroid.SHORT)
        }
        setTimeout(() => {
          backPressCountRef.current = 0
        }, 2000)
        return true // Consumes first press
      }

      // 4. Second press within 2 seconds: allow default OS exit
      return false
    }

    const backSubscription = BackHandler.addEventListener(
      "hardwareBackPress",
      onBackPress,
    )
    return () => backSubscription.remove()
  }, [webState])

  return (
    <AppErrorBoundary onReset={handleReset}>
      <View style={styles.container}>
        {/* Hide native status bar to prevent clash with web 9:41 status bar */}
        <StatusBar hidden={true} />

        <WebView
          key={reloadKey}
          ref={webViewRef}
          // Bundle Source & Whitelist
          source={{ html: webAppHtml, baseUrl: "https://localhost" }}
          originWhitelist={["*"]}
          style={styles.webView}
          // JavaScript & Storage Flags
          javaScriptEnabled={true}
          domStorageEnabled={true}
          // Media Autoplay & Inline Playback
          mediaPlaybackRequiresUserAction={false}
          allowsInlineMediaPlayback={true}
          mixedContentMode="always"
          // File Access & Security
          allowFileAccess={true}
          allowUniversalAccessFromFileURLs={true}
          allowFileAccessFromFileURLs={true}
          // Android Hardware Acceleration & Layers
          // @ts-ignore - Optional Android hardware flag
          androidHardwareAccelerationDisabled={false}
          androidLayerType="hardware"
          // Scrollbars & Viewport Zoom Lock
          showsVerticalScrollIndicator={false}
          showsHorizontalScrollIndicator={false}
          overScrollMode="never"
          scalesPageToFit={false}
          textZoom={100}
          bounces={false}
          setSupportMultipleWindows={false}
          // Loading Placeholder & State
          startInLoadingState={true}
          renderLoading={BrandLoadingView}
          // Error & Crash Lifecycle Handlers
          onMessage={handleMessage}
          onRenderProcessGone={(event) => {
            console.warn(
              "Chromium render process terminated:",
              event.nativeEvent.didCrash,
            )
            webViewRef.current?.reload()
          }}
          onError={(event) => {
            console.error("WebView loading error:", event.nativeEvent)
          }}
        />
      </View>
    </AppErrorBoundary>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BRAND_NAVY,
  },
  webView: {
    flex: 1,
    backgroundColor: BRAND_NAVY,
  },
  loadingContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: BRAND_NAVY,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  errorContainer: {
    flex: 1,
    backgroundColor: BRAND_NAVY,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  errorCard: {
    backgroundColor: BRAND_WHITE,
    borderRadius: 24,
    padding: 28,
    width: "100%",
    maxWidth: 380,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
  },
  brandDotsContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 16,
  },
  dot: {
    backgroundColor: BRAND_YELLOW,
    borderRadius: 999,
  },
  bigDot: {
    width: 14,
    height: 14,
  },
  smallDot: {
    width: 8,
    height: 8,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: BRAND_NAVY,
    marginBottom: 8,
  },
  errorMessage: {
    fontSize: 14,
    color: "#667085",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  errorDetails: {
    fontSize: 12,
    color: "#D92D20",
    backgroundColor: "#FEF3F2",
    padding: 10,
    borderRadius: 8,
    marginBottom: 16,
    width: "100%",
    fontFamily: Platform.OS === "android" ? "monospace" : "Courier",
  },
  retryButton: {
    backgroundColor: BRAND_NAVY,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 32,
    width: "100%",
    alignItems: "center",
  },
  retryButtonText: {
    color: BRAND_WHITE,
    fontSize: 15,
    fontWeight: "600",
  },
})
