import { build } from "vite"
import fs from "node:fs"
import path from "node:path"

function mobileVideoBlobPlugin() {
  return {
    name: "mobile-video-blob-plugin",
    enforce: "pre",
    load(id) {
      if (id.endsWith(".mp4")) {
        const buffer = fs.readFileSync(id)
        const b64 = buffer.toString("base64")
        return `
          const b64 = ${JSON.stringify(b64)};
          let blobUrl = '';
          try {
            const bin = atob(b64);
            const bytes = new Uint8Array(bin.length);
            for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
            const blob = new Blob([bytes], { type: 'video/mp4' });
            blobUrl = URL.createObjectURL(blob);
            if (typeof window !== 'undefined') {
              window.__SPLASH_BLOB_URL__ = blobUrl;
            }
          } catch(e) {
            console.error('Blob URL creation error:', e);
          }
          export default blobUrl;
        `
      }
      return null
    },
  }
}

async function testSingleFileGeneration() {
  console.log("Running test singlefile generation...")
  const result = await build({
    configFile: path.resolve("vite.config.ts"),
    plugins: [mobileVideoBlobPlugin()],
    build: {
      write: false,
      assetsInlineLimit: 2000000,
      rollupOptions: {
        output: {
          codeSplitting: false,
        },
      },
    },
  })

  const bundle = Array.isArray(result) ? result[0] : result
  let htmlAsset = null
  const jsChunks = []
  const cssAssets = []

  for (const item of bundle.output) {
    if (item.fileName === "index.html") {
      htmlAsset = item
    } else if (item.type === "chunk" && item.fileName.endsWith(".js")) {
      jsChunks.push(item)
    } else if (item.type === "asset" && item.fileName.endsWith(".css")) {
      cssAssets.push(item)
    }
  }

  if (!htmlAsset) {
    throw new Error("index.html not found in build output")
  }

  let html = htmlAsset.source.toString()

  // Combine and inline CSS
  const cssContent = cssAssets.map((c) => c.source.toString()).join("\n")
  // Remove existing CSS link tags
  html = html.replace(/<link[^>]*rel=["']stylesheet["'][^>]*>/gi, "")
  // Inject inlined style before </head>
  html = html.replace("</head>", `<style>\n${cssContent}\n</style>\n</head>`)

  // Combine and inline JS
  const jsContent = jsChunks
    .map((j) => j.code.replace(/<\/script>/gi, "<\\/script>"))
    .join("\n")
  // Remove existing script tags pointing to module assets
  html = html.replace(
    /<script[^>]*type=["']module["'][^>]*src=["'][^"']*assets\/[^"']*["'][^>]*><\/script>/gi,
    "",
  )
  // Inject inlined script before </body>
  html = html.replace(
    "</body>",
    `<script type="module">\n${jsContent}\n</script>\n</body>`,
  )

  console.log("Single-file HTML generated! Length:", html.length)
  console.log("Contains <style>:", html.includes("<style>"))
  console.log(
    'Contains <script type="module">:',
    html.includes('<script type="module">'),
  )
  console.log("Contains createObjectURL:", html.includes("createObjectURL"))

  // Test packaging to TypeScript constant
  const tsContent =
    `// Auto-generated by scripts/generate-mobile-bundle.js - DO NOT EDIT MANUALLY\n` +
    `export const webAppHtml: string = ${JSON.stringify(html)
      .replace(/\u2028/g, "\\u2028")
      .replace(/\u2029/g, "\\u2029")};\n`

  console.log(
    "Generated TypeScript module size:",
    (tsContent.length / 1024 / 1024).toFixed(2),
    "MB",
  )
}

testSingleFileGeneration().catch((err) => console.error(err))
